INSERT INTO ingredients (ingredient, ingredient_type) VALUES
('Шинка', 'MEAT'),
('Гриби', 'VEGETABLE'),
('Цибуля', 'VEGETABLE'),
('Ананаси', 'VEGETABLE'),
('Ковбаса', 'MEAT'),
('Чилі', 'VEGETABLE'),
('Мариновані огірки', 'VEGETABLE'),
('Перець болгарський', 'VEGETABLE'),
('Пепероні', 'MEAT'),
('Помідори', 'VEGETABLE'),
('Салямі', 'MEAT'),
('Бекон', 'MEAT'),
('Мисливські ковбаски', 'MEAT'),
('Куряче філе', 'MEAT'),
('Моцарелла', 'CHEESE'),
('Пармезан', 'CHEESE'),
('Дорблю', 'CHEESE'),
('Вершки', 'CHEESE'),
('Горошок', 'VEGETABLE'),
('Кукурудза', 'VEGETABLE'),
('Маслини', 'VEGETABLE'),
('Оливки', 'VEGETABLE'),
('Орегано', 'VEGETABLE'),
('Лимон', 'VEGETABLE'),
('Червона риба', 'SEAFOOD'),
('Кальмар', 'SEAFOOD'),
('Крабові палички', 'SEAFOOD'),
('Креветки', 'SEAFOOD'),
('Тунець', 'SEAFOOD');
