DROP TABLE IF EXISTS order_pizza;
DROP TABLE IF EXISTS pizza_ingredient;
DROP TABLE IF EXISTS customer_order;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS ingredient;

CREATE TABLE ingredient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name VARCHAR(50) NOT NULL,
    ingredient_type VARCHAR(50) NOT NULL
);

CREATE TABLE pizza (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    price_for_small INT NOT NULL,
    price_for_big INT NOT NULL,
    weight_for_small INT NOT NULL,
    weight_for_big INT NOT NULL
);

CREATE TABLE pizza_ingredient (
    pizza_id INT NOT NULL,
    ingredient_id INT NOT NULL,
    PRIMARY KEY (pizza_id, ingredient_id),
    FOREIGN KEY (pizza_id) REFERENCES pizza(id) ON DELETE NO ACTION,
    FOREIGN KEY (ingredient_id) REFERENCES ingredient(id) ON DELETE NO ACTION
);

CREATE TABLE customer_order (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
    delivery_time TIMESTAMP NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    customer_phone_number VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(50) NOT NULL,
    cc_number VARCHAR(16) NOT NULL,
    cc_expiration VARCHAR(5) NOT NULL,
    cc_vv VARCHAR(3) NOT NULL,
    price INT NOT NULL
);

CREATE TABLE order_pizza (
    order_id INT NOT NULL,
    pizza_id INT NOT NULL,
    PRIMARY KEY (order_id, pizza_id),
    FOREIGN KEY (order_id) REFERENCES customer_order(id) ON DELETE NO ACTION,
    FOREIGN KEY (pizza_id) REFERENCES pizza(id) ON DELETE NO ACTION
);